### ISSUE TITLE
crl Project 3 - RViz

### ISSUE THREAD

**Issue by zenetio** [udacity/robotics-beta-test-issues#564]
After launch, in RViz I only see RP2. No map or welcome message.

**Comment by hvpandya** [comment]
Can you attach a screenshot of your rviz window, along with any error messages you see in the terminal?

**Comment by zenetio** [comment]
It sems to be relate do move_group
![image](https://user-images.githubusercontent.com/578337/28681909-7d6ca6e2-72d1-11e7-9678-0251d1227898.png)

**Comment by hvpandya** [comment]
Have you tried restarting after waiting a minute or so? The error message says that the robot could not connect to the move_group action _server, meaning the moveit pipeline did not come up in the time it should have.

I am quite confident this should get resolved by restarting the project. If that does not work, try restarting your VM once. Let me know about your findings.

**Comment by zenetio** [comment]
I restarted the project and restarted the VM and still getting the same result. Then I tried with the latest VM and now I dont have Rviz and getting the error
[ERROR] [1501183167.964119894, 834.082000000]: couldn't resolve publisher host []
